### ISSUE TITLE
Questions about the results of the experiment

### ISSUE THREAD

**Issue by zlchen6** [VisualComputingInstitute/triplet-reid#10]
Hi，whether data augmentation is used  to get the result in your experiment?
such as Table 2 in your paper
Market-1501 SQ,
mAP :69.14%
rank-1:84.92%

**Comment by Pandoro** [comment]
As also described in the paper, we apply train and test time augmentation unless specifically described otherwise. So yes those numbers include data augmentation.

**Comment by zlchen6** [comment]
Thanks for your answer
