### ISSUE TITLE
How to use in video?

### ISSUE THREAD

**Issue by mayidu** [VisualComputingInstitute/triplet-reid#15]
Hello, the trained model how to use in video to Re-ID?

**Comment by Pandoro** [comment]
Answering this question will mean I would have to tell you simple tensorflow basics, for which there are great tutorials online. As we already told you in the other issues, this kind of question is not related to the purpose of the repository. You will have to figure this out by yourselves.

**Comment by mayidu** [comment]
Very thanks for you! You are right, I should solve these question by myself because these not problem, and when I figure it out, I will enjoy! I have solved these question in two days. Maybe I have the same question again, I know how to do. Now, I use the trained model by triplets Re-id in deep sort to track people and cars, and the result is good. Thanks you again!

**Comment by lucasb-eyer** [comment]
Glad to hear that it works well!

**Comment by taojake** [comment]
@mayidu i also want to integrate this model into deepsort, can you share your method? Thanks a lot!

**Comment by pratiksparwatwar** [comment]
@mayidu Have you used it for multi-camera tracking? If yes, please let me know how should I proceed with this.
