### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by Niculuse** [VisualComputingInstitute/triplet-reid#16]
Hello, authors!
My PC's memory is too small, thus it's very hard for me to train the model. I want to know if you can  share your model trained well. I'll appreciate it if you can provide the model weights file which is based on tensorflow.
Anyway, thanks!

**Comment by lucasb-eyer** [comment]
This is a good idea, I agree we should do this. I'm not sure if we'll get to it before the holidays yet, though. If you're in a hurry, remember that we already provide trained weights for Theano/Lasagne in the README.

**Comment by Niculuse** [comment]
Thank you first.
Unfortunately, I failed to install lasagne.Perhaps it's python version's problem. Thus, I need tensorflow's model. I'm happy to know that you can share it. 
You're very kind. Thank you again!

**Comment by Pandoro** [comment]
Hi @Niculuse ,

I just trained a model with all defaults and uploaded the [weights](https://github.com/VisualComputingInstitute/triplet-reid/releases/tag/250eb1). You can just download the zip and point the embed code to the checkpoint. Using the correct flags for both embedding and evaluation you should get the exact same results as mentioned on the release page.
