### ISSUE TITLE
how to Switch between single query and multiple query ?

### ISSUE THREAD

**Issue by ofishhaha** [VisualComputingInstitute/triplet-reid#17]
Hello authors,

I noticed that the result of SQ and MQ in the paper vary a lot.
As for the code, is it controlled by  parameter --excluder in evaluate.py?
'market1501' means MQ, while 'diagonal' means SQ.

Is it true?

**Comment by Pandoro** [comment]
Hello,

we did not implement the MQ evaluation in this code. market1501 is the correct Market-1501 SQ evaluation. Diagonal is used for other datasets with simpler evaluation protocols. For the full evaluation it would make sense to use the original Market-1501 evaluation code with slight modifications (e.g. no PCA and replacing max pooling with average pooling).

**Comment by lucasb-eyer** [comment]
In addition, note that it is important to merge the queries by averaging, not max-pooling.

**Comment by ofishhaha** [comment]
Thank you so much for your reply.
