### ISSUE TITLE
Problems wiht converting this Loss to a video-based re-id training

### ISSUE THREAD

**Issue by skidsaint** [VisualComputingInstitute/triplet-reid#18]
Hello, authors,

I'm trying to use the effective training strategies( like batch hard ) proposed in your paper to do some video-based re-id training.  I noticed that in your work you use single frame as a training sample of a person. I want to use videos like N consecutive frames as the training sample of a person, however, I found it is hard to train and get a poor result.

So if this Triplet Loss is sensitive to image or video input?

**Comment by lucasb-eyer** [comment]
No, it shouldn't be. MARS is actually video-snippets and we obtain state-of-the-art scores there too. Furthermore, we have used it in tracking datasets (i.e. videos) in [further work](http://vision.rwth-aachen.de/publication/00163/), and it performs well too.
