### ISSUE TITLE
Extracting npz weights file after training own model

### ISSUE THREAD

**Issue by pranamesh** [VisualComputingInstitute/triplet-reid#21]
Hi,
I trained the resnet-v1-50 using the train.py given here. It produces checkpoint.index, checkpoint.meta and checkpoint.data files after completion of training. However, I wanted to have the weights file as .npz file similar to the weights file provided by you for the MARS and MARKET dataset so that I can use my model with the trinet_embed.py file. Can you please suggest how can I get the .npz file after my training?

Thanks in advance.

**Comment by lucasb-eyer** [comment]
These two codes are incompatible. The `.npz` file and `trinet_embed.py` is only for our original experiments we did in Theano+Lasagne. When you train your own model here in TensorFlow, you need to use `embed.py`, but [this is all described in the README](https://github.com/VisualComputingInstitute/triplet-reid#computing-embeddings), so closing this issue.
