### ISSUE TITLE
train for apparel embedding

### ISSUE THREAD

**Issue by Chris19920210** [VisualComputingInstitute/triplet-reid#22]
Hi, I use this project for my apparel embedding project. Basically, the main for my project is to query similar clothes by an given cloth. I take the DeepFashion dataset as the train data. The positive samples for the triplet loss are the images under same sub directory, they are similar but not exactly the same. Now, I have already test several different structures for training, but the result is not satisfactory. To be specific, it sometimes leads to trivial solution, the embedding for each cloth is almost the same. And the active count never drop and  it converges very fast at somehow high loss value. Is there any suggestion for training? Thanks in advance.

**Comment by lucasb-eyer** [comment]
Hi Chris, that's an interesting project.

Yes, what you observe is exactly what we describe in Section D of the appendix of our paper, please read it.

Also, copying from [the README here](https://github.com/VisualComputingInstitute/triplet-reid#training-your-own-models):

:boom: :fire: :exclamation: **If you train on a very different dataset, don't forget to tune the learning-rate** :exclamation: :fire: :boom:

I'm closing the issue for now. Once you tried everything form above, please either let us know which of the suggestions made it work or, if it still doesn't work, feel free to re-open the issue with details on all the things you have tried and we can then try to help you further.
