### ISSUE TITLE
combine with re-ranking

### ISSUE THREAD

**Issue by Zoesxw** [VisualComputingInstitute/triplet-reid#24]
Hi, Thanks for the code, I'm new to this subject.
In the paper, you combine with re-ranking. I add a little code to compute gallery-gallery distances, but error: OOM when allocating tensor with shape[19732,19732,128].
So could you teow you combine the code with re-ranking.
Thank you!

**Comment by Pandoro** [comment]
Hi Zoesxw,

the error you mention isn't related to the re-ranking but simply based on the fact you can't compute the full gallery to gallery distance matrix. However, our eval code runs in a batched fashion, meaning this shouldn't happen and I guess you use a too large batch size. On the other hand you say you added code to compute the gallery-gallery distances, which you should simply be able to do by providing the correct files to our unaltered evaluation code.

Regarding the re-ranking, we will not release any code. For this we used the original Matlab code as provided by the authors.
