### ISSUE TITLE
IndexError: boolean index did not match indexed array along dimension 1; dimension is 3368 but corresponding boolean dimension is 19732

### ISSUE THREAD

**Issue by AsuradaYuci** [VisualComputingInstitute/triplet-reid#39]
when I followed the README.md to evaluate the embedings, i meet an error which is IndexError: boolean index did not match indexed array along dimension 1; dimension is 3368 but corresponding boolean dimension is 19732.
can you tell me how to solve it?
what's more, i am confused about these lines.
![screenshot from 2018-06-08 22 38 47](https://user-images.githubusercontent.com/37969455/41164072-df50cc50-6b6c-11e8-9660-ba68304db7a1.png)
--gallery_embeddings and --query_embeddings are use the same path of h5 files?
thanks.

**Comment by lucasb-eyer** [comment]
Could you post the full command you are executing, please? Also, from your numbers, I guess you are using the Market1501 dataset, correct?

**Comment by lucasb-eyer** [comment]
Ah, and nice you found a typo in our commandline documentation :smile: The second one (`--gallery_embeddings`) should really say "...containing the gallery embeddings", so they are not the same.

**Comment by AsuradaYuci** [comment]
Thank you for your quick reply. I solve the problem, i think the error occurred is just because i use the same path for --gallery_embeddings and --query_embeddings .  I change the path, and it runs well.

**Comment by lucasb-eyer** [comment]
Glad to hear that, and thank you for this report as it uncovered the important typo in our documentation! :)
