### ISSUE TITLE
Where is the models defined?

### ISSUE THREAD

**Issue by soulslicer** [VisualComputingInstitute/triplet-reid#46]
Good day,

Can I ask which part of the code is the training model defined? I would like to visualize it.

Also is labelling done as part of the loss function, or do you directly minimize the feature vector space?

**Comment by lucasb-eyer** [comment]
> Can I ask which part of the code is the training model defined? I would like to visualize it.

I'm somewhat confused by the question. `train.py` is for training, the model is something from `head/*` pasted onto something from `nets/*`, but all that should be obvious from the names.

> Also is labelling done as part of the loss function

what? Labeling is what humans do with a new dataset, by hand? The labels are stored in `data/*.csv` files.

> , or do you directly minimize the feature vector space?

Aaand now I'm even more confused than by anything before :smile: "minimize the feature vector space" is not something one wants to do. I'm sure you mean to ask something else, but can't think of what, please clarify.
