### ISSUE TITLE
Some error occured on computing embeddings

### ISSUE THREAD

**Issue by jry-king** [VisualComputingInstitute/triplet-reid#50]
Hello!
In order to try the model out I trained the model on market-1501 on my laptop using all the default parameters, and for convenience I only went through 10 iterations(I use python3.5.4 and tensorflow1.8.0 without gpu). When I used the slightly-trained model to compute embeddings(also on market-1501), the cmd prompted an error like this: "AttributeError: 'str' object has no attribute 'get_shape' ". Could you tell me how to solve the problem? Thanks a lot.

Here is the screenshot of the error message:
![default](https://user-images.githubusercontent.com/26543484/42446322-65e6b20e-83a8-11e8-83ec-b16228685b7a.png)

**Comment by Pandoro** [comment]
Please have a look at #40. This sounds very similar.

**Comment by jry-king** [comment]
Oh, I'm sorry for not noticing that issue, and that perfectly solved my problem. The code in release section is not up to date.
Thanks a lot for your help!

**Comment by lucasb-eyer** [comment]
> The code in release section is not up to date.

Aha, thank you for letting us know, that explains why we still get these reports even though it's long fixed! We created the release only for sharing the model file and didn't expect people to use the code there, but it makes sense they do :smiley: We'll have to update it sometime soon!
