### ISSUE TITLE
Error while trying to use pretrained tensorflow model

### ISSUE THREAD

**Issue by ml2345** [VisualComputingInstitute/triplet-reid#52]
Hey, thanks for the nice work!
I was trying to use the TF checkpoint (provided [here](https://github.com/VisualComputingInstitute/triplet-reid/releases/tag/250eb1) ). 
Steps used:
1. Create a ./files.txt in which each line is a path to an image to be embedded
2. Downloaded the checkpoint provided in Releases and put in './checkpoints/
3. Ran the following command:
python embed.py --experiment_root ./checkpoint/   --dataset ./files.txt   --filename test_embeddings.h5
However, the following error comes:
> raise IOError('`args.json` could not be found in: {}'.format(args_file))
> OSError: `args.json` could not be found in: ./checkpoint/args.json
> 
Could you please help on how to use the checkpoint of Market to extract features from images?

**Comment by Pandoro** [comment]
Hi @ml2345 ,

you can find the args file [here](https://github.com/VisualComputingInstitute/triplet-reid/issues/36), we should have put it in the release but I sadly forgot about it when making it. Just paste it into `args.json` and put it in the experiment root.

**Comment by Pandoro** [comment]
I'm closing this. It should be fairly obvious how to get it to work. If not please re-open it.

**Comment by sharadhigm** [comment]
Hi,

After adding args.json.when embed.py is run
![image](https://user-images.githubusercontent.com/46314255/53146254-8a823b00-35c9-11e9-9e3a-cc7791b3342c.png)
jsondecodeerror is popping up.Kindly guide on how to go about this.

Thanks.
