### ISSUE TITLE
How to use pretrained tensorFlow models? (question)

### ISSUE THREAD

**Issue by HuaZheLei** [VisualComputingInstitute/triplet-reid#53]
Sorry to bother you, but I have no idea that the check point you listed [here](https://github.com/VisualComputingInstitute/triplet-reid/releases/tag/250eb1) is about which net (resnet_v1, resnet_v1_50 or resnet_v1_100)? Thank you.

**Comment by lucasb-eyer** [comment]
I guess you closed the issue since you figured it out yourself? For future reference: it is a resnet_v1_50

**Comment by HuaZheLei** [comment]
@lucasb-eyer Yes. First, thank you for your excellent work. Second, I think there is something misunderstanding in README. In chapter **Computing embeddings**,

python embed.py \
    --experiment_root ~/experiments/my_experiment \
    --dataset data/market1501_query.csv \
    --filename test_embeddings.h5

should be 

python embed.py \
    --experiment_root ~/experiments/my_experiment \
    --dataset data/market1501_query.csv \
    --filename market1501_query_embeddings.h5

And this will be  consistent with chapter **Evaluating embeddings**.

**Comment by lucasb-eyer** [comment]
Good point, I just fixed it.
