### ISSUE TITLE
what is tensorflow's pretrained checkpoint output node?

### ISSUE THREAD

**Issue by taojake** [VisualComputingInstitute/triplet-reid#55]
i want to use pre-trained model in deploy, so, i want to transfer checkpoint to pb file, but when i use emb/biases node, there only freeze this node to pb, so, which node is the output for object tracking inference

**Comment by Pandoro** [comment]
I'm not sure I can completely follow your question. We don't to any object tracking. We also don't provide code for freezing the model so you will have to write it yourself. If that code doesn't work it will be hard to offer support here. I know from experience that you can get it to work though. You will have to feed the input and fetch the output from the ``endpoints['emb']`` tensor.

**Comment by arcelien** [comment]
I added a `freeze.py` file that freezes the model, here: https://github.com/arcelien/triplet-reid. It's probably easiest to add a name to `endpoints['emb']` to reference it once you freeze it.

**Comment by taojake** [comment]
I have figured out it. Thanks a lot. @arcelien

**Comment by lucasb-eyer** [comment]
FYI: I just merged @arcelien's freeze code.
