### ISSUE TITLE
model

### ISSUE THREAD

**Issue by ss199302** [VisualComputingInstitute/triplet-reid#70]
Hello, do you have a weight model for re-identification of trained personnel?

**Comment by Pandoro** [comment]
I'm not completely sure what you are asking.

If you simply want weights trained on the Market-1501 dataset, those are linked in the main ReadMe.

if with "trained personel" you mean some other dataset, the answer is no. We do not provide any weights for other datasets.

I'm closing this. In case you mean something different than the above two, feel free to re-open the issue.

**Comment by Pandoro** [comment]
As I said in my previous comment. These weights are available. You find a link in the ReadMe.
