### ISSUE TITLE
 ValueError

### ISSUE THREAD

**Issue by ss199302** [VisualComputingInstitute/triplet-reid#71]
@lucasb-eyer  Hello, I have downloaded the pre-training weight model. I want to train the marktet dataset, but when I run train.py, ValueError appears: Can't load save_path when it is None. I didn't use theano. Thank you.

**Comment by ss199302** [comment]
@lucasb-eyer  When I download your trained model, I always report errors, and I need the Pb file when I need the weighted model format, so I want to train the Markte data set myself. Thank you

**Comment by Pandoro** [comment]
This error is thrown when restoring a model from a path that is `None`. I don't really see how that can happen in our code, unless you use `--resume` and don't specify a pretrained checkpoint.

Please provide the traceback of the error.

**Comment by Pandoro** [comment]
Closing this since there was no reply for over a month.
