### ISSUE TITLE
output_name

### ISSUE THREAD

**Issue by ss199302** [VisualComputingInstitute/triplet-reid#74]
@lucasb-eyer  Hello, is the final output name of the graph of the network endpoints? I want to use 
(tf. get_default_graph(). get_tensor_by_name('% s: 0')% output_name), but I don't know the output name, can you tell me? Thank you

**Comment by Pandoro** [comment]
This depends on what exactly you want to get from the network. But I guess you are looking for the embeddings. The name for that should be `out_emb`.
