### ISSUE TITLE
How to run tensrflow pretrained model with embed.py and evaluate.py?

### ISSUE THREAD

**Issue by sharadhigm** [VisualComputingInstitute/triplet-reid#75]
Hi,
Can u kindly give the steps to run just pretrained tensorflow model with checkpoints from TF-release.
Once i run the market_1501.sh i get argument --image_root error as more than one argument given.When i run embed.py i get more arguments required error for --
![image](https://user-images.githubusercontent.com/46314255/53001420-8b439180-3450-11e9-8906-0eb65be59e85.png)
experiment_root.
![image](https://user-images.githubusercontent.com/46314255/53001499-c645c500-3450-11e9-9c09-556128b6987e.png)
Appreciate your help.Thanks in advance.

**Comment by Pandoro** [comment]
On the first issue, you are missing one '-'.

For the second issue, the image root should be a folder, not an actual image. Please read the documentation and have a look at the code to understand what it does and what arguments are expected.
