### ISSUE TITLE
Dataset not found 

### ISSUE THREAD

**Issue by anoob09** [VisualComputingInstitute/triplet-reid#84]
I got the following error 
`urllib.error.HTTPError: HTTP Error 404: Not Found`
while running this command
`!python examples/softmax_loss.py -d viper -b 64 -j 2 -a resnet50 --logs-dir logs/softmax-loss/viper-resnet50`

The [dataset](http://users.soe.ucsc.edu/~manduchi/VIPeR.v1.0.zip) has been removed I guess

**Comment by Pandoro** [comment]
You must be confusing repositories. We don't  have an example folder, nor a
softmax loss.
